feat: green blinking dot added to speed and handshake
swapnilsparsh/devsVPN pull request #51
Opened 2024-12-31 10:55 UTC by swapnilsparsh

Green Blinking Dot for Transfer and Handshake

https://github.com/user-attachments/assets/17485840-2b9b-4f3f-aae6-b25fb466904d

2024-12-31 22:59 UTC, kocmo requested changes
Umm, @swapnilsparsh - green lights should not blink all the time.

Green light in "Transfer:" line should blink once after each new transfer (receive or transmit). No more often than once per second.

Green light in "Latest Handshake:" line should blink once after each new handshake.

2025-01-02 09:09 UTC, swapnilsparsh commented
@kocmo
I’ve implemented the changes for the handshake blink as requested.

Regarding the 'Transfer' line, since the calculation is handled by the daemon rather than the frontend, implementing the specific blinking behavior would require significant changes to the frontend. Currently, the green light blinks once per second as a compromise. However, if it’s a high priority for you, I’m happy to revisit this and work on a solution.

2025-01-02 19:43 UTC, kocmo commented
@sandeepinigithub, @swapnilsparsh:

- Transfer green light should blink once when received & sent message is updated. During the rest of the time it should not show a green ball.

- Latest Handshake green light should blink once after each time handshake is updated, when handshake time gets reset to 0. During the rest of the time it should not show a green ball.

2025-01-02 20:57 UTC, sandeepinigithub commented
https://github.com/user-attachments/assets/184220b1-67cb-4600-95fc-30989aeef30f

Hi! @swapnilsparsh @kocmo 
I have made some changes
Now showing 
1. Blue dot -> for idle 
2. Green blinking -> for data rx/tx

2025-01-02 20:59 UTC, kocmo commented
Thank you, @sandeepinigithub - looks great, merging.

2025-01-02 20:59 UTC, merged